### ISSUE TITLE
Bad Dafny Code Generated

### ISSUE THREAD

**Issue by ajewellamz** [awslabs/smithy-dafny#318]
Check out https://github.com/aws/aws-database-encryption-sdk-dynamodb/
cd DynamoDbEncryption
make polymorph
look at dafny/DynamoDbEncryptionTransforms/Model/AwsCryptographyDbEncryptionSdkDynamoDbTransformsTypes.dfy
note that it doesn't compile.
Compare to the checked in version, which has a MANUAL EDIT to replace that with working code.

**Comment by robin-aws** [comment]
The rejected code looks like this:

```dafny
 modifies set tmps8 <- set t8 <- config.tableEncryptionConfigs.Values
  | t8.search.Some? 
  , t9 <- t8.search.value.versions :: t9.keyStore,
 obj <- tmps8.Modifies | obj in tmps8.Modifies :: obj
```

The issue is that this code is generally being processed with `--quantifier-syntax:3`, which can't parse quantifiers that have ranges on individual variables (the `| t8.search.Some?` range above).

**Comment by ajewellamz** [comment]
Yes, it all seems to work if I remove the --quantifier-syntax:3
