### ISSUE TITLE
Allow end users to use `Vec<u8>` for blob members

### ISSUE THREAD

**Issue by robin-aws** [awslabs/smithy-dafny#594]
We currently use `aws_smity_types::Blob`, which is the right type for future proofing, but we really want to allow customers to pass in `Vec<u8>` directly. We should contribute the missing `Into<Blob>` impl in `aws_smithy_types`, or for a shorter term fix just use `Vec<u8>` directly while waiting for that to land.

**Comment by ajewellamz** [comment]
https://github.com/smithy-lang/smithy-rs/pull/3877
Adds From to Blob

**Comment by ajewellamz** [comment]
As of aws-smithy-types 1.2.8, one can pass `&[u8]` into functions taking `Into<Blob>`.
